owner: TKS-IT
repo: status-page

sites:
  - name: CHECKS EU
    url: https://tkschecks.com
assignes:
  - TKS-IT
status-website:
  baseUrl: /status-page
  logoUrl: https://tksauditor.com/wp-content/uploads/2022/05/logo-tks-web-1-200x171.jpeg
  name: TKS Service Status
  introTitle: "**TKS Service Status**"
  introMessage: Publicly available status page for the application and services of TKS company.
