# Change these first
owner: The Key to Success S.L. # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: CHECKS EU
    url: https://tkschecks.com
  - name: CHECKS EU API
    url: https://api-focus.grupotks.com
  - name: CHECKS US
    url: https://us.tkschecks.com
  - name: CHECKS LATAM
    url: https://latam.tkschecks.com
  - name: CHECKS US-LATAM API
    url: https://api-latam.tkschecks.com
  - name: Alphabet 
    url: https://alphabet.tkschecks.com
  - name: Alphabet API
    url: https://api-alphabet.tkschecks.com
  - name: CrossCHECKS
    url: https://cross.tkschecks.com
  - name: TKS Corporative Site Worldwide
    url: https://tksauditor.com
  - name: TKS Corporative Site USA
    url: https://www.tkschecksusa.com
assignes:
  - TKS-IT
status-website:
  baseUrl: /status-page
  logoUrl: https://tksauditor.com/wp-content/uploads/2022/05/logo-tks-web-1-200x171.jpeg
  name: TKS Service Status
  introTitle: "**TKS Service Status**"
  introMessage: Publicly available status page for the application and services of TKS company.
  navbar:
    - title: TKS Service Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
